server.port=8081

spring.application.name=trainer-workload-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:h2:mem:workloaddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

app.security.m2m-secret=
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{transactionId}] %msg%n

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=
spring.activemq.password=

jms.queue.workload=trainer.workload.queue
